[package]
name = "risingwave_cmd_all"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
default = ["rw-static-link"]
rw-static-link = ["workspace-config/rw-static-link"]
rw-dynamic-link = ["workspace-config/rw-dynamic-link"]
all-udf = ["external-udf", "wasm-udf", "js-udf", "deno-udf", "python-udf"]
external-udf = ["risingwave_expr_impl/external-udf"]
wasm-udf = ["risingwave_expr_impl/wasm-udf"]
js-udf = ["risingwave_expr_impl/js-udf"]
deno-udf = ["risingwave_expr_impl/deno-udf"]
python-udf = ["risingwave_expr_impl/python-udf"]

[package.metadata.cargo-machete]
ignored = ["workspace-hack", "workspace-config", "task_stats_alloc"]

[package.metadata.cargo-udeps.ignore]
ignored = ["workspace-hack", "workspace-config", "task_stats_alloc"]

[dependencies]
anyhow = "1"
clap = { workspace = true }
console = "0.15"
const-str = "0.5"
home = "0.5"
prometheus = { version = "0.13" }
risingwave_cmd = { workspace = true }
risingwave_common = { workspace = true }
risingwave_compactor = { workspace = true }
risingwave_compute = { workspace = true }
risingwave_ctl = { workspace = true }
risingwave_expr_impl = { workspace = true }
risingwave_frontend = { workspace = true }
risingwave_meta_node = { workspace = true }
risingwave_rt = { workspace = true }
shell-words = "1.1.0"
strum = "0.26"
strum_macros = "0.26"
tempfile = "3"
tikv-jemallocator = { workspace = true, features = [
    "unprefixed_malloc_on_supported_platforms",
] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { version = "0.1" }
workspace-config = { path = "../utils/workspace-config" }
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
expect-test = "1"

[build-dependencies]
thiserror-ext = { workspace = true }
vergen = { version = "8", default-features = false, features = [
    "build",
    "git",
    "gitcl",
] }

[[bin]]
name = "risingwave"
path = "src/bin/risingwave.rs"
test = false

[lints]
workspace = true
