# RisingWave cannot compile without SIMD. #7259
#
# For some targets, there's an SIMD feature enabled by default.
# For other targets, we need to enable the feature manually.
# See `rustc --print=cfg --target=<triple>` for details.

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-feature=+avx2"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-feature=+neon"]

# Extra flags for Linux targets.
[target.'cfg(target_os = "linux")']
rustflags = [
    "-Clink-arg=-fuse-ld=lld",       #2781
    "-Clink-arg=-Wl,--no-rosegment", #4574
]

[target.x86_64-apple-darwin]
rustflags = [
    "-Ctarget-feature=+sse4.2",                             # use a generally available feature, since it's not for production
    "-Clink-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
]

[target.aarch64-apple-darwin]
rustflags = [
    # neon is enabled by default
    "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
]

# Flags for all targets.
[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable"]
