---
version: "3"
services:
  fe:
    platform: linux/amd64
    image: apache/doris:2.0.0_alpha-fe-x86_64
    hostname: fe
    environment:
     - FE_SERVERS=fe1:172.21.0.2:9010
     - FE_ID=1
    ports:
      - "8030:8030"
      - "9030:9030"
    networks:
      mynetwork:
        ipv4_address: 172.21.0.2
  be:
    platform: linux/amd64
    image: apache/doris:2.0.0_alpha-be-x86_64
    hostname: be
    environment:
     - FE_SERVERS=fe1:172.21.0.2:9010
     - BE_ADDR=172.21.0.3:9050
    depends_on:
      - fe
    ports:
      - "9050:9050"
    networks:
      mynetwork:
        ipv4_address: 172.21.0.3
  risingwave-standalone:
    extends:
      file: ../../docker/docker-compose.yml
      service: risingwave-standalone
    networks:
      mynetwork:
        ipv4_address: 172.21.0.4
  postgres-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: postgres-0
    networks:
      mynetwork:
        ipv4_address: 172.21.0.5
  grafana-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: grafana-0
    networks:
      mynetwork:
        ipv4_address: 172.21.0.6
  minio-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: minio-0
    networks:
      mynetwork:
        ipv4_address: 172.21.0.7
  prometheus-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: prometheus-0
    networks:
      mynetwork:
        ipv4_address: 172.21.0.8
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "./doris_prepare.sql:/doris_prepare.sql"
    command: tail -f /dev/null
    restart: on-failure
    networks:
      mynetwork:
        ipv4_address: 172.21.0.9
  postgres:
    image: postgres:latest
    command: tail -f /dev/null
    volumes:
      - "./update_delete.sql:/update_delete.sql"
    restart: on-failure
    networks:
      mynetwork:
        ipv4_address: 172.21.0.11
volumes:
  risingwave-standalone:
    external: false
  postgres-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
name: risingwave-compose
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.21.80.0/16
  default:
