[package]
name = "risingwave_common"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
arc-swap = "1"
arrow-array = { workspace = true }
arrow-array-deltalake = { workspace = true }
arrow-buffer = { workspace = true }
arrow-buffer-deltalake = { workspace = true }
arrow-cast = { workspace = true }
arrow-cast-deltalake = { workspace = true }
arrow-schema = { workspace = true }
arrow-schema-deltalake = { workspace = true }
async-trait = "0.1"
auto_enums = { workspace = true }
auto_impl = "1"
bitflags = "2"
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
chrono-tz = { version = "0.9", features = ["case-insensitive"] }
clap = { workspace = true }
comfy-table = "7"
crc32fast = "1"
easy-ext = "1"
educe = "0.5"
either = "1"
enum-as-inner = "0.6"
enumflags2 = { version = "0.7.8" }
ethnum = { version = "1", features = ["serde"] }
fixedbitset = "0.5"
foyer = { workspace = true }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
governor = { version = "0.6", default-features = false, features = ["std"] }
hex = "0.4.3"
http = "0.2"
humantime = "2.1"
hytra = { workspace = true }
itertools = { workspace = true }
itoa = "1.0"
jsonbb = { workspace = true }
lru = { workspace = true }
memcomparable = { version = "0.2", features = ["decimal"] }
num-integer = "0.1"
num-traits = "0.2"
number_prefix = "0.4.0"
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
parking_lot = { workspace = true }
parse-display = "0.9"
paste = "1"
pin-project-lite = "0.2"
postgres-types = { version = "0.2.6", features = [
    "derive",
    "with-chrono-0_4",
    "with-serde_json-1",
] }
prometheus = { version = "0.13" }
prost = { workspace = true }
rand = { workspace = true }
regex = "1"
reqwest = { version = "0.12.2", features = ["json"] }
risingwave-fields-derive = { path = "./fields-derive" }
risingwave_common_estimate_size = { workspace = true }
risingwave_common_metrics = { path = "./metrics" }
risingwave_common_proc_macro = { workspace = true }
risingwave_error = { workspace = true }
risingwave_pb = { workspace = true }
rust_decimal = { version = "1", features = ["db-postgres", "maths"] }
rw_iter_util = { workspace = true }
rw_resource_util = { workspace = true }
ryu = "1.0"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_default = "0.1"
serde_json = "1"
serde_with = "3"
smallbitset = "0.7.1"
speedate = "0.14.0"
stacker = "0.1"
static_assertions = "1"
strum = "0.26"
strum_macros = "0.26"
sysinfo = { version = "0.30", default-features = false }
thiserror = "1"
thiserror-ext = { workspace = true }
tinyvec = { version = "1", features = ["rustc_1_55", "grab_spare_slice"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
toml = "0.8"
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = "0.3.17"
twox-hash = "1"
url = "2"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }
http-body = "0.4.5"
tower-layer = "0.3.2"
tower-service = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.16", default-features = false }
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2"
mach2 = "0.4"

[dev-dependencies]
criterion = { workspace = true }
expect-test = "1"
more-asserts = "0.3"
pretty_assertions = "1"
rand = { workspace = true }
rusty-fork = "0.3"
tempfile = "3"

[[bench]]
name = "bench_encoding"
harness = false

[[bench]]
name = "bitmap"
harness = false

[[bench]]
name = "bench_hash_key_encoding"
harness = false

[[bench]]
name = "bench_data_chunk_encoding"
harness = false

[[bench]]
name = "bench_data_chunk_compact"
harness = false

[[bench]]
name = "bench_array"
harness = false

[lints]
workspace = true
